"use strict";
// noinspection NonAsciiCharacters
Object.defineProperty(exports, "__esModule", { value: true });
exports.items = exports.PROBLEM_WITH_PAYMENT_BUTTON_URL = exports.URL_KEYBOARD = exports.BLACK_LIST_IDS = exports.ADMIN_IDS = exports.BTC_WALLETS = exports.CARD_NUMBERS = exports.REFERRAL_PROGRAM = exports.RANDOM_CARD_CHOICE = exports.ORDER_CANCEL_DELAY = exports.PRICE_URL = exports.OPERATOR_URL = exports.MAIN_MENU_SECOND_TEXT = exports.MAIN_MENU_FIRST_TEXT = exports.PLUS_PERCENT = exports.PRICE_PLUS_RANGE = exports.MINIMUM_AMOUNT = exports.TOKEN = void 0;
const uuid_1 = require("uuid");
exports.TOKEN = '6083198455:AAEP237Shd9ct_E6zNSH5Zk5A-Q7KYkXUFA';
// Минимальная сумма для пополнения
exports.MINIMUM_AMOUNT = 200;
exports.PRICE_PLUS_RANGE = 10;
exports.PLUS_PERCENT = 10;
exports.MAIN_MENU_FIRST_TEXT = '';
exports.MAIN_MENU_SECOND_TEXT = '';
exports.OPERATOR_URL = 'https://t.me/KMRR247KUZ';
exports.PRICE_URL = 'https://clck.ru/dZG5k';
exports.ORDER_CANCEL_DELAY = 1800;
exports.RANDOM_CARD_CHOICE = true;
exports.REFERRAL_PROGRAM = true;
exports.CARD_NUMBERS = [
    '4693957558795907',
    '4890494779229475',
    '4890494787859404',
    '2200730249905585'
    //   '4890494783036734',
    //   '2200730250948458',
    //   '4890494760759407',
    //   '2200730247094564'
];
exports.BTC_WALLETS = [
    'bc1q6p2llx83lp5x365uc00a33dgdyzwpua5c2jf80',
];
exports.ADMIN_IDS = [5379818540, 5576037241, 5576037241, 1765239312
    // 123456,
    // 123456,
];
exports.BLACK_LIST_IDS = [5075709409, 1288223342, 5380183515
    // 123456,
    // 123456,
];
exports.URL_KEYBOARD = [
    ['❌ОПЕРАТОР (адреса)❌', 'https://t.me/be_alphabe'],
    ['❌Саппорт (оплаты)❌', 'https://t.me/xm_doctor'],
    ['💭ОТЗЫВЫ💭', 'https://youlink.biz/Rhlq'],
    ['📰НОВОСТИ📰', 'https://t.me/+KiZQ2fI1Mc9hNDYy'],
    ['📃ПРАВИЛА МАГАЗИНА📃', 'https://youlink.biz/RiHU'],
    ['⚔️BLACK LIST⚔️', 'https://t.me/be_alphabe'],
    ['🌐САЙТ🌐', 'https://youlink.biz/aoNe'],
    //   ['💰Хочу работу!💰', 'https://t.me/be_alphabe'],
    ['👉👉Хочу работу!👈👈', 'https://t.me/be_alphabe']
];
exports.PROBLEM_WITH_PAYMENT_BUTTON_URL = 'https://t.me/xm_doctor';
// @ts-ignore
exports.items = {
    "Кострома": {
        "Заволжский : Новый Город": [
            //      {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
            //         {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //          {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //      {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //        {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Фабричный : Берендеевка": [
            //     {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
            //      {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //      {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //    {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Фабричный : Якиманиха": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //      {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //    {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Фабричный : Первомайский": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            //      {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //          {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: uuidv4()},
            //        {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Фабричный : Ребровка": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            //   {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //      {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //   {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //    {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Центральный : Давыдовский": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            //      {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //            {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            { title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: (0, uuid_1.v4)() },
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //       {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //          {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Центральный : Октябрьский": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            //        {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //        {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            { title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: (0, uuid_1.v4)() },
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //      {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Центральный : Юбилейный": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //    {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //       {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //  {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Заволжский : Михалево": [
            //       {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
            //         {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //           {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //         {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Заволжский : Селище": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //       {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //      {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //     {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Центральный : Черноречье": [
            //    {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
            //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //   {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //        {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Заволжский : Городище": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //   {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //        {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Заволжский : Малышково": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //   {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //        {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Заволжский : Паново": [
            //    {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //   {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //        {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Заволжский : Пантусово": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //   {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            // {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
            //        {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
    },
    "Буй": {
        "Весь город": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //    {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
            //    {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
            //  {title: 'Alpha-PVP (Белая) - 2гр', price: 6400, id: uuidv4()},
            //    {title: 'Alpfa-PVP (Белая) - 0.3гр', price: 1700, id: uuidv4()},
            //     {title: 'Кристалл красный О5', price: 2050, id: uuidv4()},
            //         {title: 'АМФ 2г', price: 4750, id: uuidv4()},
            //        {title: 'АМФ1Г ️', price: 2250, id: uuidv4()},
            //    {title: 'Alpha-PVP (Цитрус) - 5гр', price: 13099, id: uuidv4()},
            //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2000, id: uuidv4()},
            //    {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
            //    {title: 'Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Гашиш 2г', price: 3900, id: uuidv4()},
            // {title: 'ТАЙНИК Mephedrone (Кристальный) - 2гр', price: 6600, id: uuidv4()},
            // {title: 'Кристалл карамель 1.0г', price: 3250, id: uuidv4()},
        ],
        "Бүй : Игумново": [
        //      {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Бүй : Корёга": [
        //   {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //   {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Бүй : Молога": [
        //   {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //   {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Буй : Афонино": [
        //  {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //      {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Буй-Волога": [
        //    {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Нерехта": {
        "Нерехта : Климушино": [
        //    {title: 'Alpha-PVP (Белая) - 0.3гр', price: 1300, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Весь город": [
            //      {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
            //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
            //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Нерехта : Молоково": [
        //  {title: 'Alpha-PVP (Белая) - 0.3гр', price: 1300, id: uuidv4()},
        //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //      {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Нерехта : Троица": [
        //    {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //      {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Волгореченск": {
        "Веняиха": [
        //    {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //         {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //       {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Весь город": [
            //      {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
            //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
            { title: 'Mephedrone (Кристальный) - 1гр', price: 3200, id: (0, uuid_1.v4)() },
        ],
        "Данилково": [
        //   {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //  {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //       {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Павшино": [
        //   {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //     {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //     {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Сидоровское": [
        //     {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //      {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Иванково 2-3 км": [
        //   {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //       {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Федорково 2-3 км": [
        //   {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //      {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //      {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //        {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Парк": [
        //   {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //       {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Галич": {
        "Галич : д. Богчино": [
        //      {title: 'Alpha-PVP (Белая) - 0.5гр', price: 2300, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //       {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //        {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Галич : Лаптиво": [
        //   {title: 'Alpha-PVP (Белая) - 0.3гр', price: 1650, id: uuidv4()},
        //    {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //        {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //          {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Галич : Лобачи": [
        //         {title: 'Alpha-PVP (Белая) - 0.3гр', price: 1650, id: uuidv4()},
        //      {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //      {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //        {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //        {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Галич : Реброво": [
        //    {title: 'Alpha-PVP (Белая) - 0.5гр', price: 2300, id: uuidv4()},
        //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //     {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Судиславль": {
        "Город": [
            //   {title: 'Alpha-PVP (Белая) - 0.3гр', price: 1650, id: uuidv4()},
            { title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: (0, uuid_1.v4)() },
            //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
            //      {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
            //      {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Судиславль : Готовка": [
        //        {title: 'Alpha-PVP (Белая) - 0.3гр', price: 1650, id: uuidv4()},
        //      {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //      {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //         {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //        {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Судиславль : Дружба": [
        //   {title: 'Alpha-PVP (Белая) - 0.3гр', price: 1650, id: uuidv4()},
        //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //      {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //      {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Шарья": {
        "Шарья : Алешунино": [
        //     {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //      {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //    {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //     {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //      {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Шарья : Ветлужский": [
        //        {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //        {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //      {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //       {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //       {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
        "Шарья : Горланиха": [
        //        {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //       {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Мантурово": {
        "Весь город": [
            { title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: (0, uuid_1.v4)() },
            //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
            //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
            //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
            //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Апраксино": {
        "Весь город": [
        //      {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
    "Яковлевское": {
        "Весь город": [
        //     {title: 'Alpha-PVP (Белая) - 0.5гр ', price: 2000, id: uuidv4()},
        //  {title: 'Alpha-PVP (Белая) - 1гр', price: 3150, id: uuidv4()},
        //     {title: 'Mephedrone (Кристальный) - 0.5гр', price: 2200, id: uuidv4()},
        //   {title: 'Alpha-PVP (Нефритовый) - 0.3гр', price: 1920, id: uuidv4()},
        //   {title: 'Mephedrone (Кристальный) - 1гр', price: 4200, id: uuidv4()},
        ],
    },
};
